### ISSUE TITLE
Missing instance `(Ord a, Ord b) => Ord (Either a b)`

### ISSUE THREAD

**Issue by ysangkok** [augustss/MicroHs#50]
This instance is [available in GHC since base-2.1](https://hackage.haskell.org/package/base-4.20.0.1/docs/Data-Either.html#t:Either), so I was hoping to find it in MicroHs too. But it doesn't seem to be there:

```
> data A = A deriving (Eq, Ord)
> data B = B deriving (Eq, Ord)
> compare (Right A) (Left B)
Exception: "./Interactive.hs": line 8, col 7: Cannot satisfy constraint: (Ord (Either B A))
```

In GHC 9.10.1 this works:

```
ghci> data A = A deriving (Eq, Ord)
ghci> data B = B deriving (Eq, Ord)
ghci> compare (Right A) (Left B)
GT
```

**Comment by augustss** [comment]
Fixed

**Comment by augustss** [comment]
Fixed

**Comment by ysangkok** [comment]
It doesn't seem to actually work... I still get the same error message. On 291aa53d5681b9b64f428bd7a8a581cac1de41c1 compiled with GHC.

**Comment by augustss** [comment]
It works for me
```
...
Type ':quit' to quit, ':help' for help
> data A = A deriving (Eq, Ord)
> data B = B deriving (Eq, Ord)
> compare (Right A) (Left B)
GT
>
```

**Comment by ysangkok** [comment]
Ah. My error was that I didn't reinstall the installed standard library in `/usr/local/lib`. Issue resolved now, many thanks.
